### ISSUE TITLE
App does not start / endless loading 

### ISSUE THREAD

**Issue by Abradolf69Lincler** [LEASYSTEMS/bubatzkarte-issues#1]
After starting the app, the display remains in the loading state (animated loading circle is moving) like shown in the screenshot below
![IMG_7745](https://github.com/LEASYSTEMS/bubatzkarte-app-issues/assets/58670596/2f465e0b-91ca-4b7f-9cfd-2d9f166454f6)

**Comment by NgLoader** [comment]
nutzt er adguard?

**Comment by NgLoader** [comment]
Are you use any vpn / dns filters like adguard?
Because our domain ``bubatzkarte.app`` is new registered so it could be blocked by that.

Is this happening everytime you open the app or just sometimes?

**Comment by NgLoader** [comment]
Closed due to inactivity.
